# The topic of LaserScan messages to subscribe to for segmentation.
scan_topic: scan

# The topic that line segments listener should publish to activate line segment computation.
deadman_topic: line_seg_deadman

# The timeout duration (seconds) for the deadman switch. If there are no message published on the deadman topic within 
# this time duration, the deadman will be activated and no line segment computations will be done.
deadman_timeout_s: 0.5

# The number of points a seed segment should contain.
# This value should be LESSER than "segment_min_points" value.
seed_segment_points: 10

# The number of points a full line segment should contain.
# This value should be GREATER than "seed_segment_points" value.
segment_min_points: 15

# The maximum distance (metre) from a seed segment point to the seed segment line.
# This value should roughly coincide with the precision of the laser device.
point_to_line_threshold_m: 0.03

# The maximum distance (metre) from a seed segment point to the predicted point on the seed segment.
point_to_point_threshold_m: 0.1

# The maximum distance (metre) to consider a data point being an outlier during region growing.
growth_outlier_threshold_m: 0.05

# The maximum number of consecutive outlier points before stopping region growth.
growth_outlier_max_count: 5

# The maximum angle (rad) difference between two segments to consider them collinear.
collinear_threshold_rad: 0.1

# The maximum distance of the shortest distance between an endpoint of one segment to the other segment which are
# are collinear.
collinear_point_segment_threshold_m: 0.1

# The frequency at which to compute the lines and publish.
update_frequency: 10.0

# The minimum line length to be published.
min_line_length_m: 0.3

# The maximum line length to be published.
# Use value <= 0 to disable the maximum limit.
max_line_length_m: 0.0

# The radius around the laser device's that will be searched.
# Laser data points outside of this radius will be ignored.
# Use value <= 0 to search as far as the max range of the LaserScan message.
search_radius_m: 0.0
